
version: "3.7"
services:

  registry:
    image: registry:latest
    ports:
      - "5000:5000"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/var/lib/neo4j/data
      - $PWD/plugins:/plugins

  digester:
    image: localhost:5000/digester
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
      - registry
    environment:
      registry_url: "http://registry:5000"
      neo4j_url: "bolt://neo4j:7687"
      neo4j_user: "${NEO4J_USER}"
      neo4j_pass: "${NEO4J_PASS}"
volumes:
  neo4jdata:
    driver: local
